version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: steam-bot-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
      - "9009:9009"  # MySQL interface
    environment:
      CLICKHOUSE_DB: steam_bot
      CLICKHOUSE_USER: steam_bot
      CLICKHOUSE_PASSWORD: steam_bot_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./scripts/clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  clickhouse_data: