const { serverErrors } = require('../src/constants/common')

module.exports = {
  ru: {

    // print_info
    start_auth: "Авторизация аккаунтов",
    with_proxy: "с прокси",
    without_proxy: "без прокси",
    last_friend_invite: "Последнее добавление в друзья",
    completed_community_tasks: "выполнил задания сообщества",
    sent_invite: "отправил заявку",
    in_blacklist: "пользователь <=%=> в черном списке",
    comment_posted: "оставил комментарий в профиле",
    joined_group: "вступил в группу",
    joined_error: "ошибка вступления в группу",
    group: "группа",
    all_accounts_logged: "Все аккаунты успешно авторизованы",
    invite_stopped: "Добавление в друзья закончено в <=%=>. Заявок отправлено <=%=>",
    reinvite: "Повторное добавление будет через <=%=> часа(ов)",
    hours: "часа(ов)",
    spam_all_finished: "Спам в ЛС закончен",
    respam: "Респам начнется через <=%=> часа(ов)",
    wall_spam_finished: "Спам по стенкам закончен в <=%=>. Комментариев отправлено <=%=>",
    statis_from_all_accounts: "Статистика по всем аккаунтам:",
    number_friends_from_all_accounts: "Количество друзей со всех аккаунтов",
    clear_comments_finished: "Очистка комментариев закончена",
    join_groups_finished: "Вступление в группы закончено",
    remove_from_friend: "Вы удалили из друзей <span class='yellow'><=%=></span>",
    were_removed_by: "<span class='yellow'><=%=></span> удалил вас из друзей",
    block_from_friend: "Заблокировал",
    new_friend: "Новый друг <=%=> добавлен на аккаунт <=%=> в <=%=>",
    delete_hold_user: "Удален друг <=%=> с аккаунта <=%=> с трейдхолдом <=%=> дней",
    clear_name_history_log: "история ников",
    clear_name_history_successfully_cleared: "успешно очищена",
    fast_auth_no_mafiles: "Вы используете быструю авторизацию но мафайлы отсутствуют, это может быть проблемой при загрузке аккаунтов. Загрузите мафайлы, или отключите быструю авторизацию",

    change_privacy: "настройки приватности",
    successfully_changed: "успешно изменены",
    change_profile: "настройки профиля",
    change_avatar: "аватар",
    avatar_successfully_changed: "успешно изменен",
    error: "ошибка",

    logged_in: "авторизировался",
    new_comment: "Новый комментарий на аккаунте",
    relogin: "Релогин",
    enter_steam_guard: "Введите стим гуард для аккаунта",
    invite_group_stopped: "Приглашение друзей в группы закончено",
    accounts_loaded: "Аккаунтов загружено",
    create_link_successfully: "ссылка создана успешно",
    invites_sent: "Заявок в друзья отправлено",
    unread_comments: "Новых комментариев: <=%=>",
    unread_invites: "Новых заявок в друзья: <=%=>",
    new_friend_request: "Новая заявка в друзья от <=%=> на аккаунте: <=%=>",
    remove_friends_started: "Удаление друзей запущено",
    remove_friends_by_price_stopped: "Удаление друзей по стоимости инвентаря завершено",
    fill_all_fields: "Заполните все поля",
    market_listing_confirmation_started: "Подтверждение продажи на маркете запущено",
    trades_confirmation_started: "Подтверждение трейдов запущено",
    succesfully_trades_confirmed: "Успешно трейдов подтверждено: ",
    succesfully_market_listing_confirmed: "Успешно продаж на маркете подтверждено: ",
    importMafile: 'Загрузите maFile к этому аккаунту, или отключите быструю авторизацию и введите Guard Код вручную',

    // swal
    unbind_licence: "Вы хотите перепривязать лицензию на другой ПК ? Программа будет выключена и автоматически привязана на том ПК, где будет запущена в след. раз. Следующая перепривязка будет доступна через 5 дней",
    clear_settings: "Вы хотите очистить все настройки ? Программа будет перезапущена",
    import_accounts_before: "Сначала загрузите аккаунты",
    new_update: "Новое обновление",
    new_update_downloaded: "Обновление загружено, вы хотите установить его сейчас ?",
    upload_only_images: "Вы можете загружать только изображения",
    mafiles_loaded: "мафайлов загружено",
    imported: "загружено",
    settings_saved: "Настройки сохранены",
    online_states_changed: "Онлайн статус изменен на выбранных аккаунтах",
    start_boost: "Накрутка часов запущена",
    stop_boost: "Накрутка часов остановлена",
    percent_invites: "Укажите какой процент заявок вы хотите удалить",
    days_offline_delete: "Укажите количество дней оффлайн для удаления из друзей",
    null_for_delete_all: "null - удалить всех",
    remove_by_steamids: "Укажите список steamid друзей, которых вы хотите удалить",
    inviter_started: "Добавление в друзья запущено",
    inviter_will_start: "Добавление в друзья начнется в",
    steamid_loaded: "SteamID загружено: <=%=>. SteamID в черном списке: <=%=>.",
    import_steamid_list: "Загрузите список steamID",
    spamming_selected_users: "Спам в ЛС запущен",
    spam_finished: "Спам в ЛС закончен",
    respam_will_be: "Респам начнется через <=%=> часа(ов)",
    choose_online_states: "Выберите онлайн статус",
    provide_message: "Укажите сообщение",
    wall_spammer_started: "Спам по стенкам запущен",
    provide_message_or_id_list: "Укажите сообщение или список steamID",
    enter_escrow_days: "Укажите количество дней трейдхолда для удаления",
    deleting_hold_users: "Удаление друзей с трейдхолдом запущено",
    start_changing_avatar: "Смена аватаров запущена",
    import_image_links: "Укажите хотя бы одну ссылку на аватар",
    ui_mode_changed: "UI Mode изменен",
    choose_accounts: "Выберите аккаунты",
    enter_url: "Укажите ссылку, которую вы хотите открыть",
    you_can_open_only_steam_links: "Вы можете открыть только Steam ссылку",
    account_not_using_mafile: "Ваш аккаунт не использует maFile",
    userid_copied: "ID скопирован в буффер обмена",
    username_copied: "Никнейм пользователя скопирован в буффер обмена",
    no_accounts_for_this_group: "Нет аккаунтов из этой группы",
    accounts_group_added: "Группа аккаунтов успешно создана",
    enter_accounts_group_name: "Укажите название группы аккаунтов",
    accounts_group_deleted: "Группа аккаунтов успешно удалена",
    no_accounts_group_with_such_name: "Нет группы аккаунтов с таким именем",
    steamids_imported: "SteamID загружено",
    enter_steamids_before_import: "Укажите стимайди перед импортом",
    start_changing_privacy: "Смена настроек приватности запущена",
    start_changing_profile: "Смена данных профиля запущена",
    input_steam_guard: "Введите Steam Guard !",
    added: "Добавлено",
    removed: "Удалено",
    statistic_for_accout: "Статистика аккаунта",
    friends_with_selected_states_pinned: "Друзья с выбранным онлайн статус закреплены",
    clear_name_history: "Вы хотите очистить историю ников с выбранных аккаунтов ?",
    clearing_name_history: "Очистка истории ников запущена",
    completing_community_tasks: "Выполнение заданий сообщества запущено",
    pin_by_message_history_started: "Закрепление по истории сообщений запущено",
    clear_comments: "Укажите ключевые слова разделенные через \",\" для удаления. Оставьте поле пустым, чтобы удалить все.",
    clear_comments_started: "Очистка комментариев запущена",
    group_joiner_started: "Вступление в группы запущено",
    group_joiner_finished: "Вступление в группы закончено",
    import_group_links: "Укажите список STEAMID64 для групп",
    enter_account_name: "Укажите имя аккаунта",
    server_error: "Ошибка сервера",
    new_username_for: "Укажите новое имя для",
    have_not_invites: "Нет заявок",
    provide_your_id: "Укажите ваш ID",
    change_language: "Вы хотите изменить язык программы ? Программа будет перезапущена",
    respam_off: "Респам выключен",
    reinvite_off: "Реинвайт выключен",
    invite_time_off: "Инвайт остановлен",
    function_stopped: "Функция остановлена",
    friends_limit: "Лимиты друзей на выбранных аккаунтах",
    invite_group_started: "Приглашение друзей в группы запущено",
    provide_group_steamid: "Укажите стимайди64 группы",
    software_id_copied: "Ваш ID скопирован в буффер обмена",
    unpin_all: "Вы действительно хотите открепить всех друзей ?",
    accept_invites_started: "Принятие заявок в друзья запущено",
    clear_incoming_invites_started: "Очистка входящих заявок запущена",
    create_invite_links_started: "Создание ссылок для приглашений запущено",
    get_api_keys_started: 'Api ключи отобразятся в консоли',
    removeByMessage: 'Укажите сообщение, или часть сообщения, по которому вы хотите удалить друзей',
    startRemoveByMessage: 'Удаляем друзей по сообщению',
    addFreeGamesStarted: 'Накрутка количества игр запущена',
    addedFreeGames: 'Добавил игры на аккаунт',

    setupProfileBackgroundStarted: 'Изменение фона запущено',
    noAvaialbleBackgrounds: 'Аккаунт не имеет фона для установки',
    backgroundSetuped: 'Новый фон установлен',

    [serverErrors.userNotFound]: 'Лицензионный ключ не найден',
    [serverErrors.somethingWentWrong]: 'Что-то пошло не так',
    [serverErrors.serverError]: 'Ошибка сервера',
    [serverErrors.licenseExpired]: 'Лицензия истекла',
    [serverErrors.invalidResponse]: 'Неправильный ответ',
    [serverErrors.invalidPC]: 'Лицензия привязана к другому ПК',
    [serverErrors.invalidRequest]: 'Ошибка в запросе'
  },
  eng: {

    // print_info

    start_auth: "Start login accounts",
    with_proxy: "with proxy",
    without_proxy: "without proxy",
    last_friend_invite: "Last friends invite",
    completed_community_tasks: "сompleted community tasks",
    sent_invite: "sent invite to",
    in_blacklist: "user <=%=> in blacklist",
    comment_posted: "posted comment",
    joined_group: "joined successfully",
    joined_error: "joined error",
    group: "group",
    all_accounts_logged: "All accounts logged successfully",
    invite_stopped: "Friends inviter finished in <=%=>. Invites sent <=%=>",
    reinvite: "Reinvite'll be in <=%=> hours",
    hours: "hours",
    spam_all_finished: "Spam all finished",
    respam: "Respam'll be in <=%=> hours",
    wall_spam_finished: "Wall spammer finished in <=%=>. Comments sent <=%=>",
    statis_from_all_accounts: "Statistic from all accounts:",
    number_friends_from_all_accounts: "Number of friends from all accounts",
    clear_comments_finished: "Comment clearing finished",
    join_groups_finished: "Groups joining finished",
    remove_from_friend: "You removed from friend <span class='yellow'><=%=></span>",
    were_removed_by: "<span class='yellow'><=%=></span> removed you from friend",
    block_from_friend: "Block",
    new_friend: "New friend <=%=> added on account <=%=> in <=%=>",
    delete_hold_user: "Friend <=%=> removed from account <=%=> with tradehold <=%=> days",
    clear_name_history_log: "name history",
    clear_name_history_successfully_cleared: "successfully cleared",
    importMafile: 'Upload a maFile for this account, or disable fast auth and enter the Guard code manually',

    change_privacy: "privacy settings",
    successfully_changed: "successfully changed",
    change_profile: "profile settings",
    change_avatar: "avatar",
    avatar_successfully_changed: "successfully changed",
    error: "error",

    logged_in: "logged in",
    new_comment: "New Comment on account",
    relogin: "Relogin",
    enter_steam_guard: "Enter Steam Guard for",
    invite_group_stopped: "Groups invite stopped",
    accounts_loaded: "Accounts loaded",
    create_link_successfully: "create link successfully",
    invites_sent: "Invites sent",
    unread_comments: "New comments: <=%=>",
    unread_invites: "New invite requests: <=%=>",
    new_friend_request: "New friend request from <=%=> on account: <=%=>",
    fast_auth_no_mafiles: "You are using fast auth, but there are no mafiles. Load mafiles, or disable fast authorization",

    // swal

    unbind_licence: "Do you want to re-bind the license to another PC? The program will be turned off and automatically linked to the PC where it will be launched in the next time. The next re-binding will be available in 5 days",
    clear_settings: "Do you want clear all settings ? The program will restarted",
    import_accounts_before: "Import accounts before",
    new_update: "New update",
    new_update_downloaded: "Update is downloaded, do you want install it now ?",
    upload_only_images: "You can upload only images",
    mafiles_loaded: "mafiles loaded",
    imported: "imported",
    settings_saved: "Settings saved",
    online_states_changed: "Online state changed on selected accounts",
    start_boost: "Hours boost started",
    stop_boost: "Hours boost stopped",
    percent_invites: "Provide how much percent invites you want remove",
    days_offline_delete: "Enter how much days friend offline for delete",
    null_for_delete_all: "null - delete all",
    remove_by_steamids: "Provide steamid friends list you want to remove",
    inviter_started: "Friends inviter started",
    inviter_will_start: "Friends inviter'll start in",
    steamid_loaded: "SteamID imported: <=%=>. SteamID in blacklist: <=%=>",
    import_steamid_list: "Import steamID list",
    spamming_selected_users: "Spam all started",
    spam_finished: "Spam all finished",
    respam_will_be: "Respam'll be in <=%=> hours",
    choose_online_states: "Choose online state",
    provide_message: "Provide a message",
    wall_spammer_started: "Wall spammer started",
    provide_message_or_id_list: "Provide message or SteamID list",
    enter_escrow_days: "Provide tradeholds days count for remove",
    deleting_hold_users: "Tradeholds removing started",
    start_changing_avatar: "Avatar change started",
    import_image_links: "Provide at least one image link",
    ui_mode_changed: "UI Mode changed",
    choose_accounts: "Choose accounts",
    enter_url: "Input a link you want to open",
    you_can_open_only_steam_links: "You can open only Steam links",
    account_not_using_mafile: "Your accounts is not using maFile",
    userid_copied: "ID copied to clipboard",
    username_copied: "Username copied to clipboard",
    no_accounts_for_this_group: "There are no accounts from this group",
    accounts_group_added: "Account group successfully created",
    enter_accounts_group_name: "Provide accounts group name",
    accounts_group_deleted: "Accounts group successfully deleted",
    no_accounts_group_with_such_name: "No accounts group with this name",
    steamids_imported: "SteamID imported",
    enter_steamids_before_import: "Provide SteamID before",
    start_changing_privacy: "Change privacy settings started",
    start_changing_profile: "Change profile settings started",
    input_steam_guard: "Provide Steam Guard !",
    added: "Added",
    removed: "Removed",
    statistic_for_accout: "Account statistic",
    friends_with_selected_states_pinned: "Friends with selected online states are pinned",
    clear_name_history: "Do you want clear name history from selected accounts ?",
    clearing_name_history: "Clearing name history started",
    completing_community_tasks: "Completing community tasks started",
    pin_by_message_history_started: "Pining by message history started",
    clear_comments: "Specify keywords separated by \",\" for remove comments. Leave empty to remove all.",
    clear_comments_started: "Clearing comments started",
    group_joiner_started: "Join groups started",
    group_joiner_finished: "Join groups finished",
    import_group_links: "Provide group STEAMID64 list",
    enter_account_name: "Provide account name",
    server_error: "Server error",
    new_username_for: "Provide new name for",
    have_not_invites: "No invites",
    provide_your_id: "Provide your ID",
    change_language: "Do you want change program language ? The program will restart",
    respam_off: "Respam stopped",
    reinvite_off: "Reinvite stopped",
    invite_time_off: "Invite stopped",
    function_stopped: "Function stopped",
    friends_limit: "Friend limits on selected accounts",
    invite_group_started: "Groups invite started",
    provide_group_steamid: "Provide group steamid64",
    software_id_copied: "Your ID is copied to clipboard",
    unpin_all: "Do you really want to unpin all friends ?",
    accept_invites_started: "Accepting invites started",
    clear_incoming_invites_started: "Clearing incoming invites started",
    create_invite_links_started: "Create invites link started",
    remove_friends_started: "Remove friends started",
    remove_friends_by_price_stopped: "Remove friends by inventory price completed",
    fill_all_fields: "Fill all fields",
    market_listing_confirmation_started: "Market listing confirmation started",
    trades_confirmation_started: "Trades confirmation started",
    succesfully_trades_confirmed: "Successfully trades confirmed: ",
    succesfully_market_listing_confirmed: "Successfully market listing confirmed: ",
    get_api_keys_started: 'Api keys will be displayed in the console',
    removeByMessage: 'Enter the message, or part of the message by which you want to remove friends',
    startRemoveByMessage: 'Removing friends by message',
    addFreeGamesStarted: 'Increasing games count started',
    addedFreeGames: 'Added games to account',

    setupProfileBackgroundStarted: 'Setuping background started',
    noAvaialbleBackgrounds: 'Account doesn\'t own any backgrounds',
    backgroundSetuped: 'Set new background',

    [serverErrors.userNotFound]: 'License key is not found',
    [serverErrors.somethingWentWrong]: 'Something went wrong',
    [serverErrors.serverError]: 'Server error',
    [serverErrors.licenseExpired]: 'License has expired',
    [serverErrors.invalidResponse]: 'Invalid response',
    [serverErrors.invalidPC]: 'The license key is linked to another PC',
    [serverErrors.invalidRequest]: 'Invalid request'
  }
}